In [1]:
# Model No. 3 SVM Model for a9a
from sklearn import svm
from joblib import Memory
from sklearn.datasets import load_svmlight_file
mem = Memory("./mycache")

@mem.cache
def get_data():
    data = load_svmlight_file('a9a.txt')
    return data[0], data[1]

X, y = get_data()

________________________________________________________________________________
[Memory] Calling __main__-C%3A-Users-ybxYB-AppData-Local-Temp-ipykernel-23723983.get_data...
get_data()
_________________________________________________________get_data - 0.1s, 0.0min


In [2]:
from sklearn.svm import SVC
from joblib import Memory
from sklearn.datasets import load_svmlight_file
from sklearn import model_selection
from sklearn.model_selection import train_test_split,KFold
import numpy as np
import matplotlib.pyplot as plt
mem = Memory("./mycache")

@mem.cache
def get_data():
    data = load_svmlight_file('a9a.txt')
    return data[0], data[1]

X, y = get_data()

X_train, X_test, y_train, y_test = train_test_split(X,y)
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)
kfold = model_selection.KFold(n_splits=5)
model = svclassifier
results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold)
print(results)
print("Accuracy:", results.mean()*100)
print(model.get_params())

________________________________________________________________________________
[Memory] Calling __main__-C%3A-Users-ybxYB-AppData-Local-Temp-ipykernel-1207657492.get_data...
get_data()
_________________________________________________________get_data - 0.1s, 0.0min
[0.8458231  0.8540131  0.85135135 0.84766585 0.84009009]
Accuracy: 84.77886977886978
{'C': 1.0, 'break_ties': False, 'cache_size': 200, 'class_weight': None, 'coef0': 0.0, 'decision_function_shape': 'ovr', 'degree': 3, 'gamma': 'scale', 'kernel': 'rbf', 'max_iter': -1, 'probability': False, 'random_state': None, 'shrinking': True, 'tol': 0.001, 'verbose': False}


In [3]:
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)
kfold = model_selection.KFold(n_splits=5)
model = svclassifier
results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold)
print(results)
print("Accuracy:", results.mean()*100)

[0.84336609 0.8482801  0.8519656  0.8482801  0.84234234]
Accuracy: 84.68468468468468


In [4]:
svclassifier = SVC(kernel='poly')
svclassifier.fit(X_train, y_train)
kfold = model_selection.KFold(n_splits=5)
model = svclassifier
results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold)
print(results)
print("Accuracy:", results.mean()*100)

[0.8450041  0.85462735 0.85217035 0.8458231  0.83701884]
Accuracy: 84.69287469287468


In [5]:
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)
results = svclassifier.score(X_test, y_test)
print(results)
print("Accuracy:", results.mean()*100)

0.8464562093108955
Accuracy: 84.64562093108955


In [6]:
@mem.cache
def get_test():
    data = load_svmlight_file('a9a.t')
    return data[0], data[1]

X_test, y_test = get_test()

svclassifier = SVC(kernel='linear')
svclassifier.fit(X, y)
results = svclassifier.score(X_test, y_test)
print("Accuracy: %.2f%%" % (results * 100.0))

________________________________________________________________________________
[Memory] Calling __main__-C%3A-Users-ybxYB-AppData-Local-Temp-ipykernel-667350064.get_test...
get_test()
_________________________________________________________get_test - 0.0s, 0.0min
Accuracy: 84.98%
